// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get android => FirebaseOptions(
        apiKey: dotenv.get('FIREBASE_API_KEY_ANDROID'),
        appId: '1:73325700547:android:00e0469c998f20ed834976',
        messagingSenderId: '73325700547',
        projectId: 'hydrosync-tracker',
        storageBucket: 'hydrosync-tracker.firebasestorage.app',
      );

  static FirebaseOptions get ios => FirebaseOptions(
        apiKey: dotenv.get('FIREBASE_API_KEY_IOS'),
        appId: '1:73325700547:ios:4f79a45b20e61d1e834976',
        messagingSenderId: '73325700547',
        projectId: 'hydrosync-tracker',
        storageBucket: 'hydrosync-tracker.firebasestorage.app',
        iosBundleId: 'com.rakin.hydrosync',
      );

  static FirebaseOptions get windows => FirebaseOptions(
        apiKey: dotenv.get('FIREBASE_API_KEY_WINDOWS'),
        appId: '1:73325700547:web:c008d0c67d833147834976',
        messagingSenderId: '73325700547',
        projectId: 'hydrosync-tracker',
        authDomain: 'hydrosync-tracker.firebaseapp.com',
        storageBucket: 'hydrosync-tracker.firebasestorage.app',
      );
}
